const avs_directory_subgraph_url = process.env.AVS_DIRECTORY_SUBGRAPH_URL
const eigenlayer_delegation_subgraph_url = process.env.EIGENLAYER_DELEGATION_SUBGRAPH_URL

export { avs_directory_subgraph_url, eigenlayer_delegation_subgraph_url }
